### PR TITLE
created terraform directory

### PR DESCRIPTION
**Pull request by Tomelin**

### CODE REVIEW

**Comment by Tomelin** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # local_file.foo will be created
+ resource "local_file" "foo" {
      + content              = "foo!"
      + content_base64sha256 = (known after apply)
      + content_base64sha512 = (known after apply)
      + content_md5          = (known after apply)
      + content_sha1         = (known after apply)
      + content_sha256       = (known after apply)
      + content_sha512       = (known after apply)
      + directory_permission = "0777"
      + file_permission      = "0777"
      + filename             = "./foo.tmp"
      + id                   = (known after apply)
    }

  # null_resource.default will be created
+ resource "null_resource" "default" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```
</details>

* :arrow_forward: To **apply** this plan, comment:
  ```shell
  atlantis apply -d terraform
  ```
* :put_litter_in_its_place: To **delete** this plan and lock, click [here](http://platform_atlantis:4141/lock?id=Tomelin%252Fterraform-atlantis%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
  ```shell
  atlantis plan -d terraform
  ```
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this Pull Request, comment:
  ```shell
  atlantis apply
  ```
* :put_litter_in_its_place: To **delete** all plans and locks from this Pull Request, comment:
  ```shell
  atlantis unlock
  ```

**Comment by Tomelin** [comment]
atlantis plan -d terraform

**Comment by rafael-tomelin** [comment]
atlantis apply -d terraform

**Comment by Tomelin** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform` workspace: `default`

**Pull request merged**
